[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = "if not v.demo and not v.wip then "
position = 'before'
payload = '''if not (v.set == "Joker" and v.rarity == "zero_secret") then '''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = "v.unlocked = true"
position = 'after'
payload = '''end'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = "if (v.set == 'Voucher' or v.set == 'Joker') and not v.demo then "
position = 'before'
payload = '''if v.rarity ~= "zero_secret" then '''
match_indent = true

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = "viable_unlockables[#viable_unlockables+1] = v"
position = 'after'
payload = '''end'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = "play_sound('highlight1', nil, 0.5)"
position = 'before'
payload = '''if G.P_CENTERS[_achievement].rarity == "zero_secret" then
	play_sound('zero_infinity_fanfare', nil, 0.5)
else'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = "play_sound('foil2', 0.5, 0.4)"
position = 'after'
payload = '''end'''
match_indent = true

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/overrides.lua"]'
pattern = '''self.children.center = SMODS.create_sprite(self.T.x, self.T.y, self.T.w, self.T.h, "Joker", G.j_locked.pos)'''
position = 'before'
payload = '''if _center.hidden_pos then
self.children.center = SMODS.create_sprite(self.T.x, self.T.y, self.T.w, self.T.h, _center.atlas, _center.hidden_pos)
else'''
match_indent = true

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/overrides.lua"]'
pattern = '''self.children.center = SMODS.create_sprite(self.T.x, self.T.y, self.T.w, self.T.h, "Joker", G.j_locked.pos)'''
position = 'after'
payload = '''end'''
match_indent = true

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/overrides.lua"]'
pattern = '''if self.children.back then self.children.back:remove() end'''
position = 'before'
payload = '''if _center.set == 'Joker' and not _center.unlocked and not self.params.bypass_discovery_center and _center.hidden_soul_pos then
	if self.children.floating_sprite then self.children.floating_sprite:remove() end
	local atlas_key = _center[G.SETTINGS.colourblind_option and 'hc_atlas' or 'lc_atlas'] or _center.atlas or _center.set
    self.children.floating_sprite = SMODS.create_sprite(self.T.x, self.T.y, self.T.w, self.T.h, atlas_key, self.config.center.hidden_soul_pos)
    self.children.floating_sprite.role.draw_major = self
    self.children.floating_sprite.states.hover.can = false
    self.children.floating_sprite.states.click.can = false
end'''
match_indent = true

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/card_draw.lua"]'
pattern = '''if self.config.center.soul_pos and (self.config.center.discovered or self.bypass_discovery_center) then'''
position = 'at'
payload = '''if self.config.center.soul_pos and (self.config.center.discovered or self.bypass_discovery_center or (not self.config.center.discovered and not self.config.center.unlocked and self.config.center.hidden_soul_pos)) then'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''local locked_card = Card(G.your_collection.T.x + G.your_collection.T.w/2 - G.CARD_W/2, G.your_collection.T.y, G.CARD_W, G.CARD_H, G.P_CARDS.empty, card_center.set == 'Voucher' and G.v_locked or G.j_locked)'''
position = 'at'
payload = '''local locked_card
local locked_card = card_center.set == "Joker" and card_center.rarity == "zero_secret" and Card(G.your_collection.T.x + G.your_collection.T.w/2 - G.CARD_W/2, G.your_collection.T.y, G.CARD_W, G.CARD_H, G.P_CARDS.empty, card_center, {bypass_discovery_center = true, bypass_discovery_ui = true}) or Card(G.your_collection.T.x + G.your_collection.T.w/2 - G.CARD_W/2, G.your_collection.T.y, G.CARD_W, G.CARD_H, G.P_CARDS.empty, card_center.set == 'Voucher' and G.v_locked or G.j_locked)
if card_center.set == "Joker" and card_center.rarity == "zero_secret" then
	locked_card.children.center:set_sprite_pos(locked_card.config.center.hidden_pos)
	locked_card.children.floating_sprite:set_sprite_pos(locked_card.config.center.hidden_soul_pos)
	locked_card:set_edition("e_zero_occult",true,true)
end
'''
match_indent = true
